/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./src/**/*.{html,js}",
    "./pages/**/*.{html,js}",
    "./components/**/*.{html,js}",
  ],

  darkMode: "class",

  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e3dbfd",
        "on-tertiary-fixed": "#3f3a54",
        "secondary-fixed": "#e4e2e6",
        "on-surface-variant": "#a6acb3",
        "on-error-container": "#ff9993",
        primary: "#b2c5ff",
        "surface-container-highest": "#20262c",
        "error-container": "#7f2927",
        "on-secondary-fixed-variant": "#5b5b5f",
        "inverse-surface": "#f9f9fc",
        "on-primary-fixed": "#003991",
        "primary-container": "#0040a1",
        "secondary-fixed-dim": "#d5d4d8",
        "primary-dim": "#9db7ff",
        "tertiary-fixed-dim": "#d5cdee",
        "on-secondary-container": "#c0bec3",
        "on-surface": "#e0e6ed",
        "secondary-dim": "#9e9da1",
        background: "#0c0e10",
        "tertiary-dim": "#d5cdee",
        "on-secondary-fixed": "#3f3f43",
        outline: "#70767d",
        "on-secondary": "#1f2023",
        "surface-container-lowest": "#000000",
        "tertiary-container": "#e3dbfd",
        "surface-dim": "#0c0e10",
        "surface-bright": "#262d33",
        "on-background": "#e0e6ed",
        surface: "#0c0e10",
        "surface-tint": "#b2c5ff",
        "outline-variant": "#42494f",
        "secondary-container": "#3b3b3f",
        "on-primary-container": "#c0cfff",
        "primary-fixed-dim": "#c6d3ff",
        "primary-fixed": "#dae2ff",
        "on-tertiary-fixed-variant": "#5b5672",
        "inverse-on-surface": "#545557",
        "on-error": "#490106",
        "surface-container-low": "#111416",
        "surface-container-high": "#1b2025",
        "error-dim": "#bb5551",
        "on-primary": "#003a93",
        error: "#ee7d77",
        tertiary: "#f1ebff",
        "inverse-primary": "#0156d2",
        secondary: "#9e9da1",
        "on-primary-fixed-variant": "#0053cc",
        "on-tertiary": "#5a5570",
        "on-tertiary-container": "#524c68",
        "surface-variant": "#20262c",
        "surface-container": "#161a1e",
        monolith: {
          background: "#0c0e10",
          surface: "#111416",
          border: "#1b2025",
          text: "#e0e6ed",
          muted: "#a6acb3",
          accent: "#b2c5ff",
          hover: "#1b2025",
          error: "#ee7d77",
          success: "#82e3b9",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
